// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62QqGqGGfIeReUn9Wli5CM3MKTuBlzmE',
    appId: '1:429792658004:web:130e4651cefd409f96e3c1',
    messagingSenderId: '429792658004',
    projectId: 'togetherly-6161',
    authDomain: 'togetherly-6161.firebaseapp.com',
    storageBucket: 'togetherly-6161.firebasestorage.app',
    measurementId: 'G-GVNC7GDXM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcsWY_eVIllV0hFBDDn734I9dFaYGkMQY',
    appId: '1:429792658004:android:18a59e0fe6dc078e96e3c1',
    messagingSenderId: '429792658004',
    projectId: 'togetherly-6161',
    storageBucket: 'togetherly-6161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFIRVii0FeYntBZ4-0sqd_VZgf6B20xRk',
    appId: '1:429792658004:ios:ca9e376e384780c196e3c1',
    messagingSenderId: '429792658004',
    projectId: 'togetherly-6161',
    storageBucket: 'togetherly-6161.firebasestorage.app',
    iosBundleId: 'com.birlikteyapp.birlikteyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFIRVii0FeYntBZ4-0sqd_VZgf6B20xRk',
    appId: '1:429792658004:ios:ca9e376e384780c196e3c1',
    messagingSenderId: '429792658004',
    projectId: 'togetherly-6161',
    storageBucket: 'togetherly-6161.firebasestorage.app',
    iosBundleId: 'com.birlikteyapp.birlikteyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC62QqGqGGfIeReUn9Wli5CM3MKTuBlzmE',
    appId: '1:429792658004:web:21a34c82d161cff696e3c1',
    messagingSenderId: '429792658004',
    projectId: 'togetherly-6161',
    authDomain: 'togetherly-6161.firebaseapp.com',
    storageBucket: 'togetherly-6161.firebasestorage.app',
    measurementId: 'G-FZNEDE8YQZ',
  );

}