// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZfibYOqOEDoriccTivWAptuMdWg2alzo',
    appId: '1:880853149618:web:3933dafc4b4b085b1b66ab',
    messagingSenderId: '880853149618',
    projectId: 'togetherly-staging',
    authDomain: 'togetherly-staging.firebaseapp.com',
    storageBucket: 'togetherly-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgp7vk6pPUYEd95oy-bumhehUiV2f116Y',
    appId: '1:880853149618:android:64f68a1c39ae90051b66ab',
    messagingSenderId: '880853149618',
    projectId: 'togetherly-staging',
    storageBucket: 'togetherly-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCubclIxmuKZURidnSy9LhJtn30sf4POCo',
    appId: '1:880853149618:ios:437d1c9cfaa6c8ef1b66ab',
    messagingSenderId: '880853149618',
    projectId: 'togetherly-staging',
    storageBucket: 'togetherly-staging.firebasestorage.app',
    iosBundleId: 'com.birlikteyapp.birlikteyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCubclIxmuKZURidnSy9LhJtn30sf4POCo',
    appId: '1:880853149618:ios:437d1c9cfaa6c8ef1b66ab',
    messagingSenderId: '880853149618',
    projectId: 'togetherly-staging',
    storageBucket: 'togetherly-staging.firebasestorage.app',
    iosBundleId: 'com.birlikteyapp.birlikteyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZfibYOqOEDoriccTivWAptuMdWg2alzo',
    appId: '1:880853149618:web:e111be52e87397471b66ab',
    messagingSenderId: '880853149618',
    projectId: 'togetherly-staging',
    authDomain: 'togetherly-staging.firebaseapp.com',
    storageBucket: 'togetherly-staging.firebasestorage.app',
  );

}